version: "2.1"

services:
  web:
    build:
      context: ./command_project_
      dockerfile: Dockerfile.prod
    command: gunicorn lifts_project.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - web_logs:/home/app/web/logs
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - web_logs:/home/app/web/logs

    ports:
      - "8123:80"
    depends_on:
      - web

  bot:
    build:
      context: ./command_project_
      dockerfile: Dockerfile.bot

    restart: always
    volumes:
      - media_volume:/home/app/web/media
      - bot_logs:/home/app/bot/logs
    env_file:
      - ./.env.bot.prod
    depends_on:
      - web
      - nginx
volumes:
  postgres_data:
  static_volume:
  media_volume:
  web_logs:
  bot_logs:
