version: "v2.14"

services:
  web:
    build:
      context: ./command_project_
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 127.0.0.1:8000
    restart: always
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:16.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 8000:8000
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
