version: "2.1"

services:
  web:
    build:
      context: ./command_project_
      dockerfile: Dockerfile
    command: gunicorn lifts_project.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media

    expose:
      - 8000
    env_file:
      - ./.env.prod
    # depends_on:
    #   - db

    # db:
    #   image: postgres:alpine
    #   restart: always
    #   volumes:
    #     - postgres_data:/var/lib/postgresql/data/
    #   env_file:
    #     - ./.env.dev.db
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media

    ports:
      - "8123:80"
    depends_on:
      - web

  bot:
    build:
      context: ./command_project_
      dockerfile: Dockerfile.bot

    restart: always
    volumes:
      - media_volume:/home/app/web/media
    ports:

      - 433
    env_file:
      - ./.env.bot.dev
    depends_on:
      # - db
      - web
      - nginx
volumes:
  postgres_data:
  static_volume:
  media_volume:
